all: program1 program2 program3


program1: program1.cpp readInput.h readInput.cpp
	g++ -std=c++11 -o program1 program1.cpp readInput.cpp

program2: program2.cpp readInput.h readInput.cpp
	g++ -std=c++11 -o program2 program2.cpp readInput.cpp

program3: program3.cpp readInput.h readInput.cpp
	g++ -std=c++11 -o program3 program3.cpp readInput.cpp


