run: digraph.o circle.o program.o
	g++ digraph.o circle.o program.o -o run

digraph.o: digraph.cpp
	g++ -c -std=c++11 digraph.cpp

circlo.o: circle.cpp
	g++ -c -std=c++11 circle.cpp

program.o: program.cpp
	g++ -c -std=c++11 program.cpp
