run: Call.o CallCenter.o PriorityQueue.o Simulation.o
	g++ Call.o CallCenter.o PriorityQueue.o Simulation.o -o run
Call.o: Call.cpp
	g++ -c -std=c++11 Call.cpp

CallCenter.o: CallCenter.cpp
	g++ -c -std=c++11 CallCenter.cpp

PriorityQueue.o: PriorityQueue.cpp
	g++ -c -std=c++11 PriorityQueue.cpp

Simulation.o: Simulation.cpp
	g++ -c -std=c++11 Simulation.cpp
